

CREATE TABLE Project (
	PID VARCHAR(16) NOT NULL,
	Project_Name VARCHAR(30) NOT NULL,
	Build_Date DATE NOT NULL,
	End_Date DATE NOT NULL,
	PRIMARY KEY (PID);
	
CREATE TABLE Line_Code (
	Line_Code VARCHAR(20) NOT NULL,
	Slock BIGINT NOT NULL,
	PRIMARY KEY (Line_Code);	

CREATE TABLE Hours_Charged (
	Hour_Code VARCHAR(20) NOT NULL,
	Num_Hours INT UNSIGNED NOT NULL,
	Line_Code VARCHAR(20) NOT NULL,
	PRIMARY KEY (Hour_Code),
	INDEX Column 3 (Line_Code),
	CONSTRAINT FK__Line_Code FOREIGN KEY (Line_Code) REFERENCES Line_Code (Line_Code));
	
CREATE TABLE WBS (
	WBS_ID VARCHAR(20) NOT NULL,
	WBS_Name VARCHAR(50) NOT NULL,
	Hour_Code VARCHAR(20) NOT NULL,
	PRIMARY KEY (WBS_ID),
	CONSTRAINT FK__Hours_Charged FOREIGN KEY (Hour_Code) REFERENCES Hours_Charged (Hour_Code));
	
CREATE TABLE Product (
	Product_Code VARCHAR(20) NOT NULL,
	Product_Name VARCHAR(50) NOT NULL,
	PRIMARY KEY (Product_Code));
	
CREATE TABLE WBS (
	WBS_ID VARCHAR(20) NOT NULL,
	WBS_Name VARCHAR(50) NOT NULL,
	Hour_Code VARCHAR(20) NOT NULL,
	PRIMARY KEY (WBS_ID),
	CONSTRAINT FK__Hours_Charged FOREIGN KEY (Hour_Code) REFERENCES Hours_Charged (Hour_Code));
	
CREATE TABLE Describes (
	Product_Code VARCHAR(20) NOT NULL,
	WBS_ID VARCHAR(20) NOT NULL,
	PRIMARY KEY (Product_Code, WBS_ID),
	INDEX FK_Describes_WBS (WBS_ID),
	CONSTRAINT FK_Describes_Product FOREIGN KEY (Product_Code) REFERENCES Product (Product_Code),
	CONSTRAINT FK_Describes_WBS FOREIGN KEY (WBS_ID) REFERENCES WBS (WBS_ID));
	
CREATE TABLE Contains (
	PID VARCHAR(16) NOT NULL,
	Product_Code VARCHAR(20) NOT NULL,
	PRIMARY KEY (PID, Product_Code),
	INDEX FK_Contains_Product (Product_Code),
	CONSTRAINT FK_Contains_Product FOREIGN KEY (Product_Code) REFERENCES Product (Product_Code),
	CONSTRAINT FK_Contains_Project FOREIGN KEY (PID) REFERENCES Project (PID));
	
CREATE TABLE Bug (
	BID VARCHAR(30) NOT NULL,
	B_Status VARCHAR(1) NOT NULL,
	Product_Code VARCHAR(20) NOT NULL,
	WBS _ID VARCHAR(20) NOT NULL,
	PRIMARY KEY (BID),
	CONSTRAINT FK__Product FOREIGN KEY (Product_Code) REFERENCES Product (Product_Code),
	CONSTRAINT FK__WBS FOREIGN KEY (WBS _ID) REFERENCES WBS (WBS_ID));
	
